spring:
  datasource:
    url: jdbc:mysql://47.95.172.23:3306/digitalCloudPlatUser?serverTimeZone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: Link!13726284740
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8800